version: '3.4'

services:
  kokrjachapi:
    image: ${DOCKER_REGISTRY-}kokrjachapi
    build:
      context: .
      dockerfile: KokrjachApi/Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/events.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    ports:
      - "5001:443"

  events:
    image: ${DOCKER_REGISTRY-}events
    build:
      context: .
      dockerfile: Events/Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/events.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    ports:
      - "5002:443"
      - "8080:80"

  database:
    image: "mysql/mysql-server:latest"
    container_name: database
    environment:
      MYSQL_DATABASE: "kokrjach_events"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./datadir:/var/lib/mysql
    ports:
      - "3306:3306"
