version: '3.4'

services:
  kokrjachapi:
    image: ${DOCKER_REGISTRY-}kokrjachapi
    build:
      context: .
      dockerfile: KokrjachApi/Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/events.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    ports:
      - "5001:443"

  events:
    image: ${DOCKER_REGISTRY-}events
    build:
      context: .
      dockerfile: Events/Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/events.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    ports:
      - "5002:443"
      - "8080:80"
